security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost:      12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: $2y$12$3bdV/GQ2ptq/DouEiQ40xuZ3P8WTqkYrxfzG4ndjg/5qCB8YZC.Eu!, roles: [ 'ROLE_USER' ] }
                    admin: { password: $2y$12$V0QnVvKqmnxm1ZLy66S6I./AcckZTY.tUoFyishydqbCOHSWWesjO!, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt))/
            security: false

        static:
            pattern:  ^/(css|images|img|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        app:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: login_check
                login_path: login
            logout:
                path:   logout
                target: home

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY } # requires_channel: https 
        - { path: ^/admin/, roles: ROLE_ADMIN }
